import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Template from './src/models/Template.js';

dotenv.config();

function getBodyVariableIndices(content) {
  const matches = (content || '').match(/\{\{(\d+)\}\}/g) || [];
  return [...new Set(matches.map((m) => parseInt(m.replace(/\D/g, ''), 10)))].sort((a, b) => a - b);
}

function buildBodyExample(content, category = '') {
  const indices = getBodyVariableIndices(content);
  if (indices.length === 0) return undefined;

  const isAuth = String(category).toLowerCase() === 'authentication';
  const samples = indices.map((n) => {
    if (isAuth && n === 1) return '123456';
    if (n === 1) return 'Customer';
    if (n === 2) return 'Starter';
    if (n === 3) return 'monthly';
    if (n === 4) return 'https://replysys.com/pay';
    return `sample_${n}`;
  });

  return { body_text: [samples] };
}

function buildMetaComponents({ hasMedia, mediaType, mediaUrl, headerText, content, footerText, buttons = [], category = '' }) {
  const components = [];
  const isAuthentication = String(category).toLowerCase() === 'authentication';

  if (!isAuthentication && hasMedia && mediaType && mediaType !== 'none') {
    const comp = { type: 'HEADER', format: mediaType.toUpperCase() };
    if (mediaUrl) comp.example = { header_handle: [mediaUrl] };
    components.push(comp);
  } else if (!isAuthentication && headerText) {
    const hasVars = /\{\{\d+\}\}/.test(headerText);
    const comp = { type: 'HEADER', format: 'TEXT', text: headerText };
    if (hasVars) comp.example = { header_text: ['sample_value'] };
    components.push(comp);
  }

  const bodyExample = buildBodyExample(content, category);
  const bodyComp = { type: 'BODY', text: content };
  if (bodyExample && !isAuthentication) bodyComp.example = bodyExample;
  if (isAuthentication) {
    bodyComp.add_security_recommendation = true;
  }
  components.push(bodyComp);

  if (isAuthentication) {
    components.push({ type: 'FOOTER', code_expiration_minutes: 10 });
  } else if (footerText) {
    components.push({ type: 'FOOTER', text: footerText });
  }

  return components;
}

async function run() {
  await mongoose.connect(process.env.MONGODB_URI);
  const template = await Template.findOne({ category: 'utility', status: 'draft', name: 'replysys_payment_reminder' });

  const generated = buildMetaComponents({
    hasMedia: template.hasMedia,
    mediaType: template.mediaType,
    mediaUrl: template.mediaUrl,
    headerText: template.headerText,
    content: template.content,
    footerText: template.footerText,
    buttons: [],
    category: template.category,
  });

  const bodyIdx = generated.findIndex((c) => c.type === 'BODY');
  if (bodyIdx >= 0) {
    const example = buildBodyExample(template.content, template.category);
    if (example) {
      generated[bodyIdx].example = example;
    }
  }

  console.log("=== SEEDED COMPONENTS IN DB ===");
  console.log(JSON.stringify(template.components, null, 2));
  console.log("\n=== GENERATED BY SUBMIT FUNCTION ===");
  console.log(JSON.stringify(generated, null, 2));

  process.exit(0);
}

run();
